### ISSUE TITLE
Any chance of adding a few examples?

### ISSUE THREAD

**Issue by ScottPhillips** [NickEnbachtov/SimpleAI#1]
It would be awesome if there were a few examples in the repo as well, just to see what it does and to get up and running quicker....

Thanks!

**Comment by NickEnbachtov** [comment]
Hello, 
I will add few examples (to get up and running quicker) in the repo in next two days. I will report.

**Comment by NickEnbachtov** [comment]
I added example project. You can find it (SimpleAI example project class version) in the repo or download on release page https://github.com/NickEnbachtov/SimpleAI/releases/tag/v1.6

Also there is a plugin version of SimpleAI (https://github.com/NickEnbachtov/plugins-template-library-docs), plugin version more comfortable in use
